import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import PageHeader from "../../components/PageHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Theo Harris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const footer = (
    <footer>
      <div className="border-t border-slate-500 mt-6 py-6 text-center text-slate-400">
        <p>Developed with ❤️ by Theo Harris</p>
      </div>
    </footer>
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-2xl px-6">
          <PageHeader />
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
